### ISSUE TITLE
Request for Database File

### ISSUE THREAD

**Issue by Mehdi-ferjani** [ulasahin/HotelManagementWebSite#1]
Hello Canfer Ulaş Şahin,

Thank you for sharing this project. I’m interested in implementing it and would like to request access to the database file to fully set it up. Could you please share it or guide me on how to generate it?

Best regards,

**Comment by ulasahin** [comment]
Hello,

I apologize for the delay in responding to your message. Of course, I can assist you with this. This application is a project created for learning purposes, so it doesn't currently have a pre-filled database. If you've examined the project, you'll have noticed that it consists of a back-end and a front-end.

On the back-end side, in the file located at "EasyStay-core/src/main/resources/application.properties", there's a line in the second row:
spring.datasource.url=jdbc:postgresql://localhost:5432/EasyStay.

The "EasyStay" part here represents the name of the database. You can start by either changing this name or creating your database with this name. Additionally, your database port should be 5432.

This project is compatible with a PostgreSQL database. Of course, you can use any database type you prefer (MySQL, etc.), but I found PostgreSQL more suitable as it works better with Java and Spring Boot in terms of optimization.

To be honest, switching the database might require extra effort as you would also need to make changes in certain parts of the code. :D

**Comment by Mehdi-ferjani** [comment]
Hello,

Thank you for the explanation .
Thanks again!

Best regards,
